// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigeonReviewProject.DBContext;

#nullable disable

namespace PigeonReviewProject.Migrations
{
    [DbContext(typeof(PigeonDBContext))]
    [Migration("20220920142335_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PigeonReviewProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Gym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Pigeon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pigeon");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.PigeonCategory", b =>
                {
                    b.Property<int>("PigeonId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PigeonId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PigeonCategories");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.PigeonOwner", b =>
                {
                    b.Property<int>("PigeonId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("PigeonId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("PigeonOwners");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PigeonId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PigeonId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviewers");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Owner", b =>
                {
                    b.HasOne("PigeonReviewProject.Models.District", "District")
                        .WithMany("Owners")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.PigeonCategory", b =>
                {
                    b.HasOne("PigeonReviewProject.Models.Category", "Category")
                        .WithMany("PigeonCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PigeonReviewProject.Models.Pigeon", "Pigeon")
                        .WithMany("PigeonCategories")
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Pigeon");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.PigeonOwner", b =>
                {
                    b.HasOne("PigeonReviewProject.Models.Owner", "Owner")
                        .WithMany("PigeonOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PigeonReviewProject.Models.Pigeon", "Pigeon")
                        .WithMany("pigeonOwners")
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pigeon");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Review", b =>
                {
                    b.HasOne("PigeonReviewProject.Models.Pigeon", "Pigeon")
                        .WithMany("Reviews")
                        .HasForeignKey("PigeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PigeonReviewProject.Models.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pigeon");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Category", b =>
                {
                    b.Navigation("PigeonCategories");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.District", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Owner", b =>
                {
                    b.Navigation("PigeonOwners");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Pigeon", b =>
                {
                    b.Navigation("PigeonCategories");

                    b.Navigation("Reviews");

                    b.Navigation("pigeonOwners");
                });

            modelBuilder.Entity("PigeonReviewProject.Models.Reviewer", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
